### ISSUE TITLE
interpolate.py error

### ISSUE THREAD

**Issue by semel1** [jhogsett/EMA-VFI-WebUI#120]
Trying to evaluate your code. Unfortunately upon run:
`D:\Restoration\EMA-VFI-WebUI-1.4>python interpolate.py`

got an error: 

```
Traceback (most recent call last):
  File "interpolate.py", line 13, in <module>
    from webui_utils.simple_utils import sortable_float_index
  File "D:\Restoration\EMA-VFI-WebUI-1.4\webui_utils\simple_utils.py", line 96, in <module>
    mantissa_width : float | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'```
```
Tried both version of recommended installations.  
EMA-VFI works properly

Running:

`python webui.py`

throws an error:

```
D:\Restoration\EMA-VFI-WebUI-1.4>python webui.py
Traceback (most recent call last):
  File "webui.py", line 10, in <module>
    from webui_utils.file_utils import create_directories
  File "D:\Restoration\EMA-VFI-WebUI-1.4\webui_utils\file_utils.py", line 8, in <module>
    def is_safe_path(path : str | None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by jhogsett** [comment]
@semel1 I haven't seen this before. It sounds like the Python type hinting isn't being recognized by Python. It's failing the first time it encounters one of these hints while importing. 

I'm not sure what to recommend, perhaps:
- Check which Python version is being used and whether type hints are supported by it (I use Python 3.10.9 installed via Anaconda)
- Seeing if a brief test.py file runs OK with Python code that includes type hinting
- Trying on another computer (I use Windows 11)
- Some [Googling](https://stackoverflow.com/questions/72644693/new-union-shorthand-giving-unsupported-operand-types-for-str-and-type) shows that this is the new "union" syntax, and, technically, it **is** a _type error_ because the `str` type does not have a `__or__()` function.  I'm never informed of an error when I run the code on any of my systems (nor has another user reported it). It makes me think there might be a _strict_ Python option that's not enabled for me by default, but perhaps is for you. I don't have an immediate fix, but there are suggestions in that SO about avoiding problems like this, so I'll need to look into that.

**Comment by semel1** [comment]
I'm running Python 3.7.2 installed via Anaconda.
In accordance with https://docs.python.org/3/library/typing.html
Type hinting supported since Python version 3.5
"ttest.py file runs OK with Python code that includes type hinting"? - I'm not fluent in Python coding.
I use: 
Windows10,
RTX9090, 
CUDA Version: 12.2  

I'll try on another computer.

**Comment by jhogsett** [comment]
It's the Python version. I did a bit more reading; the new new union style and type error don't occur in the version of Python (3.10.9) that the project is based on. Trying on another computer may work, but you may also run into the same issue. My recommendation is to create a new Anaconda environment based on Python 3.10.9 and install everything into it.

**Comment by jhogsett** [comment]
In case it's helpful, I found an online guide on setting up a new Anaconda environment with a specific Python version: https://numdifftools.readthedocs.io/en/stable/how-to/create_virtual_env_with_conda.html. I apologize that my tool doesn't have a one-click installer. It's on my long range radar, but not something planned in the near term.

**Comment by semel1** [comment]
I'll try it on another rig.
Meantime I'm doing full system backup and will  update my Python 3.7.2 to 3.10.9

**Comment by semel1** [comment]
I've installed Python v.3.10 and now everything works just fine.
I'm very impressed of your application.
Just some comments:

1. The most important is the frame interpolation quality.
Frame interpolation by EMA-VFI introduces significant amount of distorted images that increases if you use "Resynthesize Video"
Currently I'm using FlowFrames application with RIFE interpolation AI model V.4.4.
https://nmkd.itch.io/flowframes
The interpolation quality almost perfect. May be it makes sense to add this model to your app.
Below the samples of original frames
![00000001](https://github.com/jhogsett/EMA-VFI-WebUI/assets/53234248/031d6122-5194-413c-9676-664d6077f93d)
![00000003](https://github.com/jhogsett/EMA-VFI-WebUI/assets/53234248/fb85591b-092c-4483-8722-9989da4ca554)
Below the interpolated frame created by RIFE
![00000002](https://github.com/jhogsett/EMA-VFI-WebUI/assets/53234248/4c118989-c0a4-40a2-ab78-9a32f83b103c)
And this is interpolation using EMA-VFI-WebUI 
![image](https://github.com/jhogsett/EMA-VFI-WebUI/assets/53234248/96080202-8e7b-4393-9960-5d02c45c0245)
2.For cleaning I'm using "FAST_Anime_VCR" 
https://github.com/Kiteretsu77/FAST_Anime_VSR
this is CUGAN with TensorRT implementation that runs 1080P on my RTX3090 almost real-time and performs pretty good noise
reduction (using pro-denoise3x-up2x.pth) even with scale factor = 1

It could be very useful to extend input/output formats (ProRes/AVI-ffv1/... etc.) directly and in "File Conversion"
Is it possible to perform "Frame Cleansing and Image Stabilization" without frame interpolation?

**Comment by jhogsett** [comment]
@semel1 thanks so much for the evaluation and feedback, I truly appreciate it.

> I'm very impressed of your application.

Thanks! I wrote it for myself but I aspire to make it as useful to others as it is to me.

> Currently I'm using FlowFrames application with RIFE interpolation AI model V.4.4.
https://nmkd.itch.io/flowframes
The interpolation quality almost perfect. May be it makes sense to add this model to your app.
Below the samples of original frames

Thank you, that's great feedback. On my feature list is to make the application VFI engine-agnostic, so that it can be used with EMA-VFI, VFIformer, or any other engine that can be operated from Python code. In the best case, adding support for a new engine would be a matter of writing some Python _wrapper_ code to handle the specifics of a particular engine. As an example, the VFIformer engine (what this app used originally) will be able to work this way.

> 2.For cleaning I'm using "FAST_Anime_VCR"
https://github.com/Kiteretsu77/FAST_Anime_VSR
this is CUGAN with TensorRT implementation that runs 1080P on my RTX3090 almost real-time and performs pretty good noise
reduction (using pro-denoise3x-up2x.pth) even with scale factor = 1

I also have plans to put Real-ESRGAN behind a Python wrapper so the upscaling engine can be swapped out.

> It could be very useful to extend input/output formats (ProRes/AVI-ffv1/... etc.) directly and in "File Conversion"

This ought to work now for some things. In most cases where the application asks for a .mp4 file, it's feeding the entry directly to FFmpeg as the input argument, so any input type that FFmpeg supports should also work. E.g., I've gotten it to work with crazy things like .rm (real media) and PNG input sequences. Give it a try.

The application itself works entirely in lossless space (24-bit color PNG frames and 16-bit WAV audio). I don't know much about what's needed for the richer formats -- I'm guessing better than 8-bits-per-channel color, more than basic 2 channel audio, etc. This is an area I will need to become educated about, or find someone to collaborate. 

Note, the "Create Custom Remix" on the final tab let's you provide raw arguments directly to the two FFmpeg processes that assemble the content into the final remix content, so you have complete control over how the lossless content is transformed by FFmpeg:
- Create video clips from the final set of processed PNG frames
- Combine WAV audio with the above clips into scene videos (these get concatenated into the final remix video w/o reencoding)

> Is it possible to perform "Frame Cleansing and Image Stabilization" without frame interpolation?

I don't think so. The interpolation is what's doing both the cleansing and stabilization. Here's how:
- In the following, imagine there are three frames of an action sequence, and we're throwing out the middle frame completely, to be replaced by interpolation
    | FRAME 1 | ~~FRAME 2~~ | FRAME 3 |
- My understanding is the engine will find features that appear in both outer frames FRAME 1 & FRAME 3, use that information to estimate motion flow, then compute the necessary warping to synthesize the between frame
- Features that appear in one frame but not in the other are semi-dissolved out in the new between frame, and become much less noticeable. I.e. a dust particle that appears only in one of the two outer frames will be mostly interpolated away
-  Stabilization occurs because frame _positional noise_ (e.g. loose sprockets on an 8mm film reproduction) is automatically smoothed out. Imagine that FRAME 2 above is shifted due to a bad sprocket. That shift is not present in the resynthesized frame.
-  So the replaced FRAME 2 has none of the original visual or positional noise present in the original frame, and has mainly features that only exist in both FRAME 1 and FRAME 3
- _Video Resynthesis_ repeats this process for every frame in the video that has two adjacent outer frames.

**Comment by jhogsett** [comment]
@semel1 the interpolation quality of EMA VFI is actually quite good, but it does have limitations. The example you cite seems to exceed its motion detection limit, so it perceives the hand movement as the disappearance and reappearance of unrelated objects. It does a good job with  higher framerate starting content. I created a series of videos comparing VFIformer and EMA VFI and you can clearly see the pros and cons of both. See here for all of my test videos: https://github.com/MCG-NJU/EMA-VFI/issues/4

Here is an example video just created using some of the processing features (resizing, inflation, upscaling, but not resynthesis): https://www.youtube.com/watch?v=8Ce98WZM4ws
